name: Build Docker Image
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        description: Whether to deploy the build images
jobs:
  build:
    if: "!(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]'))"
    strategy:
      matrix:
        scheme: [small, full]
    name: Build TeXLive [${{ matrix.scheme }}-scheme]
    runs-on: ubuntu-latest
    steps:
      - name: Setup enviroment
        run: |
          echo "SCHEME=${{ matrix.scheme }}" >> "$GITHUB_ENV"
          echo "TAG=ghcr.io/xu-cheng/texlive-${{ matrix.scheme }}" >> "$GITHUB_ENV"
          echo "VERSION=$(date "+%Y%m%d")"  >> "$GITHUB_ENV"
      - name: Setup Git repository
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: scheme=${{ env.scheme }}
          platforms: linux/amd64,linux/arm64
          load: true
          tags: texlive-${{ env.scheme }}
      - name: Test pdflatex
        run: |
          docker run --rm texlive-$SCHEME pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{newtxtext}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data texlive-$SCHEME python3 /opt/texlive/bin/texliveonfly test.tex
          file test.pdf | grep -q ' PDF '
      - name: Test latexindent
        run: |
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{newtxtext}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data texlive-$SCHEME latexindent test.tex
        if: "matrix.scheme == 'full'"
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
        if: "github.ref == 'refs/heads/master'"
      - name: Deploy
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: scheme=${{ env.scheme }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAG }}:${{ env.VERSION }},${{ env.TAG }}:latest
        if: "github.ref == 'refs/heads/master' && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.deploy))"
